heroui-inc/tailwind-variants

src/index.d.ts

Fixed `class, className` type error and auto-suggestion hint.
- Add `ClassValue` generic for `ClassProp`.
- Provide default types for `TVVariants, TVCompoundVariants, TVDefaultVariants` for better type inference.
- Define `function tv` as a `TV` type to be easily exported.
---

fix: class and className of TVProps

---

src/__tests__/transformer.test.ts
src/config.d.ts
src/index.d.ts
src/transformer.js

- `responsiveVariants` set to `false` by default.
```tsx
import { tv } from 'tailwind-variants';
const button = tv(
{
variants: {
color: {
primary: '...',
secondary: '...'
},
size: {
sm: '...',
md: '...'
}
}
},
{
// Transform all variants under every screen.
responsiveVariants: true,
// Transform all variants under the specified screens.
responsiveVariants: ["sm", "md"],
// Transform specified variants.
responsiveVariants: {
// Transform color variant under every screen.
color: true,
// Transform size variant under specified screens.
size: ["sm", "md"]
}
}
);
const App = () => {
return (
<button className={button({ size: { initial: "sm", lg: "md" } })}>
Label
</button>
);
};
```
```javascript
const { withTV } = require('tailwind-variants/transformer');
/**
* Tailwind Config
*
* @type …
```

feat: on-demand transform

---

src/transformer.js

Exclude transform without `responsiveVariants` config to avoid warnings in the terminal.
-  Updated the regular expression for `extend`.
---

fix: exclude transform without responsive variants

---

src/__tests__/tv.test.ts
src/index.d.ts
src/index.js

Avoiding empty strings in the result to get a cleaner DOM.
DOM example with empty result.
```html
<div class>...</div>
```
```html
<div>...</div>
```
---

feat: avoid empty strings in the result

---

src/index.d.ts

The TypeScript types were behaving very slow and after some digging it was due to a circular reference from `ReturnType<TV>`. Swapping that out with `TVReturnType` drastically improves the experience in the editor.
There are a bunch of other issues with the types related to missing generic arguments and such that I plan on helping fix in future PRs, but wanted to get this out there since it's a small fix with a big performance improvement.
The videos below show the difference in time for errors appearing before and after this change.
https://user-images.githubusercontent.com/25914066/234464472-79fb3025-0448-48aa-bdee-43781b6c4111.mov
https://user-images.githubusercontent.com/25914066/234464481-0a6dbc7b-7c83-4e95-8ffb-260dd5ed75e5.mov

Use `TVReturnType` to prevent circular references

---

package.json
pnpm-lock.yaml
src/index.d.ts

closes: https://github.com/nextui-org/tailwind-variants/issues/59
closes: https://github.com/nextui-org/tailwind-variants/issues/56
closes: https://github.com/nextui-org/tailwind-variants/issues/55
closes: https://github.com/nextui-org/tailwind-variants/issues/53
- Add generics to `EV` and `TVReturnType` for type inference.
- Upgrade `tailwind-merge` to the latest version.
- Upgrade `typescript` to the latest version.
---

fix: support typescript 5.1.3

---

src/index.js

Closes #64 
Closes #58 
Tailwind merge was disabled when custom tw-merge config passed
---

fix: default config assigned to the config prop

---

src/utils.js

#65 
Use recursion to replace flat.
---
Just code golfing performance, inspired by @TIMMLOPK
Original
```
CVA x 931,787 ops/sec ±0.62% (89 runs sampled)
CVA with tailwind-merge x 503,360 ops/sec ±1.16% (88 runs sampled)
TV with slots x 97,211 ops/sec ±0.44% (91 runs sampled)
TV without slots x 113,086 ops/sec ±0.57% (90 runs sampled)
Fastest is CVA
```
@TIMMLOPK's branch
```
CVA x 957,529 ops/sec ±0.54% (90 runs sampled)
CVA with tailwind-merge x 475,375 ops/sec ±1.19% (86 runs sampled)
TV with slots x 151,382 ops/sec ±3.36% (86 runs sampled)
TV without slots x 180,776 ops/sec ±0.53% (88 runs sampled)
Fastest is CVA
```
This branch
```
CVA x 940,169 ops/sec ±0.57% (91 runs sampled)
CVA with tailwind-merge x 489,335 ops/sec ±0.79% (90 runs sampled)
TV with slots x 181,157 ops/sec ±0.72% …
```

feat: improving performance 2

---

src/__tests__/tv.test.ts
src/index.js

Fixes #74 
`compoundSlots` did not work properly when setting a boolean variant to `false`. This resolves that issue.
---

fix: support `false` variants when using `compoundSlots`

---

package.json
src/__tests__/tv.test.ts
src/index.d.ts
src/index.js
src/utils.js

Fixes #48 
This adds support for slot level variant overrides. This is useful in a variety of situations:
1. Component libraries that provide slot level class name functions:
```typescript
const {base,tab} = tv({...})
<Tabs className={() => base()}>
<Tab className={({ isSelected }) => tab({isSelected})}>
Settings
</Tab>
</Tabs>
```
1. Reusing styles for vary similar components.
```typescript
const {base,item} = tv({...})
<Nav className={base()}>
<NavItem className={item({isActive: activeItem === 'foo'})}>foo</NavItem>
<NavItem className={item({isActive: activeItem === 'bar'})}>bar</NavItem>
</Nav>
```
---

feat: Add support for slot level variant overrides

---

src/index.d.ts

This PR aligns the `ClassValue` type with with corresponding type from `tailwind-merge`. In particular, the old type was missing `0` and `false` as possible values. This makes it difficult to use tailwind-merge + tailwind-variants together since the base class typing is different between the two projects.
---

fix: align class value with tailwind-merge

---

src/__tests__/tv.test.ts
src/index.js

Fixes #104 
The change to `joinObjects` was causing extended slots to be mutated incorrectly.
---

fix: prevent extend from modifying extended slots

---

src/index.d.ts

This reworks `TVReturnType` to use `keyof` on the original generic objects so that go to definition will work properly on slots.
I'm trying to get the same to work for `base`, but that one's a little more complex since that will require some amount of shifting the options into a generic of it's own which has some complexities.
https://github.com/nextui-org/tailwind-variants/assets/25914066/c72599d0-af10-416d-945c-e8128e54e9e3
---

feat: support goto definition for slots

---

src/__tests__/tv.test.ts
src/index.js
src/utils.d.ts
src/utils.js

Compound slots fixed, compound slots applied even when the variant was undefined or did not match 
---

fix: compound slots with variants

---

src/index.d.ts
tsconfig.json

fix(tsconfig): add  exactOptionalPropertyTypes

---

src/__tests__/tv.test.ts
src/index.js

PR #118 broke compoundSlots when using boolean variants. This PR fixes that by checking if the slot value is an array and then either doing `.includes()` or full equality checking.
I also updated the tests to do length checks on the class names to ensure that no extra class names slip in, as this was the issue that this PR fixes. I noticed in our usage of tailwind-variants with boolean variants that we were always getting the true value, even when false. The length checks should help prevent false positives.

Fix `compoundSlots` with boolean variants

---

src/__tests__/createTV.test.ts
src/index.d.ts
src/index.js

This adds a new `createTV` function that allows users to create a configured version of `tv` with tailwind-merge or other config. This is similar to using `defaultConfig` but supports multiple separate `tv` functions.
Fixes https://github.com/nextui-org/tailwind-variants/issues/95
Fixes https://github.com/nextui-org/tailwind-variants/issues/18
Docs PR here: https://github.com/nextui-org/tailwind-variants-docs/pull/19
---

feat: add `createTV` utility to create a `tv` function from a config

---

src/__tests__/tv.test.ts
src/utils.js

Fixes the `mergeObjects` function that was only allowing string for variants.
When using the `extend` property, it's used the function `mergeObjects` but it doesn't handle array inputs only string.
---

fix: variant as array when extending

---

src/index.d.ts

Fixes https://github.com/nextui-org/tailwind-variants/issues/15
Fixes https://github.com/nextui-org/tailwind-variants/issues/44
Fixed types of the extend variants by asserting slots and providing default value (`{}`).
---

fix: types of the extend variants

---

jest.config.js
package.json
pnpm-lock.yaml
src/__tests__/createTV.test.ts
src/__tests__/transformer.test.ts
src/__tests__/tv.test.ts
src/__tests__/utils.test.ts
src/setupTests.ts

This updates the test suite to use a custom Jest matcher for better error messages and stack traces.
---

Improve test suite

---

src/__tests__/tv.test.ts
src/index.js

After upgrading to the latest version of `tailwind-variants`, we noticed a small UI regression where a component which specified only a `false` variant was continually using that, despite `true` being specifically passed in.
It looks like this occurs because of the logic to always fall back to the `false` variant if the initial value isn't found:
https://github.com/nextui-org/tailwind-variants/blob/a26d801f13f97af726a0c206ae413cd5543ea7ff/src/index.js#L220
This PR addresses that by changing where the fallback happens. I've also added a couple of tests which cover the case that currently fails.
It's an odd case so hopefully this won't be impacting many other users! In our case, we actually realised that this API choice wasn't ideal and ended up implementing an alternative workaround. …

fix: Support false-only variant with fallback behaviour

---

clean-package.config.json

Adjusted the exports types target
For projects with `moduleResolution` set to `NodeNext`, `exports` has priority over `types` in `package.json`, as the current types target in `exports` is incorrect, it's currently throwing an error:
---

fix: adjust path for types

---

README.md
src/__tests__/transformer.test.ts
src/__tests__/tv.test.ts
src/transformer.d.ts
src/transformer.js

Add support for passing custom aliases in the custom TV Transformer.
Currently, the transformer checks the files's content against the `"tailwind-variants"` constant to check whether or not the file should be transformed.
However, when creating a custom TV instance and importing it, the transformer will ignore it as it's not matching `"tailwind-variants"`.
```ts
// @/lib/tv.ts
import { createTV } from 'tailwind-variants';
export type { VariantProps } from 'tailwind-variants';
export const tv = createTV({
// my custom twMergeConfig.
});
```
The proposed change adds a configuration object to the `withTV` function to configure aliases:
```js
// tailwind.config.js
const { withTV } = require('tailwind-variants/transformer')
/** @type {import('tailwindcss').Config} */
module.exports = withTV({ …
```

feat(transformer): support custom aliases

---

package.json
src/__tests__/tv.test.ts
src/index.js

fix: support multi-level extend for `compoundVariants`

---

src/__tests__/tv.test.ts
src/utils.js

When using Arrays on a extended variant it was returning `[object object]`.
By changing the order of the function `mergeObjects` to first check if is an `array` it work as expected (joining the arrays).
---

fix mergeObjects order

---

src/transformer.d.ts

Add `transformerConfig` type to `withTV` function.
Currently we are missing this type in the `transformer.d.ts` file and that causes this issue:
I was going to open an issue but noticed I could just open a PR directly.

fix(transformer): add transformer config type to withTV function

---

benchmark.js
package.json
pnpm-lock.yaml

Fixes #134 
Adds CVA to the benchmarks since a lot of folks often want to compare the perf of the two libraries.
There are only two benchmarks for CVA since it doesn't support slots.
```
TV without slots & tw-merge (enabled) x 743,372 ops/sec ±0.62% (93 runs sampled)
TV without slots & tw-merge (disabled) x 1,006,953 ops/sec ±0.27% (95 runs sampled)
TV with slots & tw-merge (enabled) x 304,484 ops/sec ±1.21% (96 runs sampled)
TV with slots & tw-merge (disabled) x 343,062 ops/sec ±1.04% (98 runs sampled)
TV without slots & custom tw-merge config x 729,188 ops/sec ±1.28% (96 runs sampled)
TV with slots & custom tw-merge config x 404,001 ops/sec ±0.22% (98 runs sampled)
CVA without slots & tw-merge (enabled) x 1,039,518 ops/sec ±0.20% (100 runs sampled)
CVA without slots & tw-merge …
```

docs: add `cva` to benchmarks

---

src/__tests__/transformer.test.ts
src/index.js

cc @codecaaron
While trying to use `responsiveVariants` with `slots` present, any responsive props passed were not output in the component's classname.
---
Ensure that responsive classnames are applied to `base` correctly when slots are also used.
Here's a minimal code example of the issue:
```tsx
// example
const button = tv(
{
base: 'inline-flex cursor-pointer gap-2 ...',
slots: {
icon: 'w-4 h-4 aspect-square pointer-events-auto',
},
variants: {
size: {
xs: 'text-xs',
sm: 'text-sm',
md: 'text-md',
},
},
},
{ responsiveVariants: true },
);
const Button = ({ children, icon: Icon, ...rest }) => {
const { base, icon } = button(rest)
return (
<button {...rest} className={base()} ref={ref}>
{children}
{Icon && <Icon className={icon()} />}
</button>
);
};
// responsive variants won't work as …
```

(fix): responsive variants for base when slots are present
